### ISSUE TITLE
-m (minLength) option removed from hts_QWindowTrim, but does not exist in hts_CutTrim

### ISSUE THREAD

**Issue by marade** [s4hts/HTStream#232]
Commit 86c939a9095bc19c6053efd689da7635dbd001ce removes the option from hts_QWindowTrim, because we're now supposed to use hts_CutTrim instead, but hts_CutTrim does not have a minLength option, so we can now no longer filter by minimum length with the pipeline?

**Comment by samhunter** [comment]
Hi @marade, there is now a new tool called hts_LengthFilter (https://github.com/s4hts/HTStream/tree/master/hts_LengthFilter) to take care of this step.

**Comment by marade** [comment]
Ah good. Thanks for the assistance.

**Comment by samhunter** [comment]
No problem, thanks for feedback! 

The idea is that all length filtering can be handled by a single tool, so that statistics for this type of filtering are in the same place instead of spread across many different tools.
