### ISSUE TITLE
hts_Primers - error message

### ISSUE THREAD

**Issue by adamerum** [s4hts/HTStream#241]
Hello, 
I am trying (for the first time) to use hts_Primers to remove primers to which diversity spacers have been added to create sequence diversity for amplicon sequencing, using the following command: 
` hts_Primers -1 X_R1.fastq.gz -2 X_R2.fastq.gz -P Fprimer.fasta -Q Rprimer.fasta
`

However, I receive the following error:
![image](https://user-images.githubusercontent.com/46504849/99858970-93f45a80-2b43-11eb-87b8-55febcef8c06.png)
Do you have any idea what could be causing this? 
Thank you in advance.

**Comment by msettles** [comment]
Hmm, so you've likely found an edge case bug we haven't seen yet and need to address. Of the top of my head I'd say your primer is longer than the read? Anyway you could isolate that read and pass it on, OR if you could provide the whole dataset I can find it. Also with diversity spacers you want to use the -l option so if your primer is say ACTGATAT and you have 1-4 diversity basepair proceeding your primer then  you'd use -l 4

**Comment by samhunter** [comment]
Hi @adamerum also could you let us know what version of HTStream you are using? If it isn't v1.3.3 please try updating. I don't remember the exact error, but we found a little bug in reading fasta files with spaces in the sequence name. That got fixed recently and the fix is present in the latest release (https://github.com/s4hts/HTStream/releases/tag/v1.3.3)

**Comment by adamerum** [comment]
Hi @msettles and @samhunter, thank you both for your fast and helpful feedback. I can confirm after modifying the command to include -l and updating to v1.3.3 hts_Primers is running smoothly, so I believe as you anticipated it was an issue with reading the fasta file. Thank you again for your help!

**Comment by samhunter** [comment]
Hi @adamerum it sounds like I should close this issue, thanks for the followup!
