### ISSUE TITLE
How to cite HTStream? :-)

### ISSUE THREAD

**Issue by mickey-spongebob** [s4hts/HTStream#243]
Dear HTStream team :-)

Hope this finds you well. Thank you for the really nice tool! I would like to cite HTStream (I specifically used SuperDeduper) but I'm not sure how to do it. I found the original work [https://dl.acm.org/doi/10.1145/2808719.2811568] (I assume). Should I go with this or would you (your team) prefer a different more updated way to acknowledge your work :-)

Cheers :-)

**Comment by samhunter** [comment]
Hi Mickey,

The algorithm and idea is the same, and most of the authors are the same, we just re-implemented in HTStream. It might be best to cite that publication with a link to the GitHub repo. Maybe something like:

"Duplicate reads were discarded using SuperDeduper (Petersen 2015, re-implemented as part of HTStream, https://github.com/s4hts/HTStream)."

But that's just a suggestion. 

Sam

**Comment by mickey-spongebob** [comment]
Hi Sam,

Thank you so much! :-) 

Take care and wishing you well!

Cheers :-)
