### ISSUE TITLE
citation?

### ISSUE THREAD

**Issue by Tgrandis** [s4hts/HTStream#245]
Hello.
Thanks for making superdeduper available here. I use this programme for cleaning up WGS reads and thus I would like to ackmowledge the developers in publication. However, I could not find a reference for the hts-superdeduper programme on the Github site or in the readme documentation or anywhere else for that matter.
Please provide a citation (in the readme file or elsewhere) so that users can give you credit for the work you have done.
Thanks in advance,
Hugo

**Comment by samhunter** [comment]
Hi Hugo,

Thanks for your suggestion. I'm glad that HTStream has been useful for you, and thank you for acknowledging our hard work in making it available! Unfortunately we don't have a publication quite yet. Please just cite the GitHub page for now. I have updated the readme to reflect this, and also added a citation to an earlier implementation of the SuperDeduper algorithm.

**Comment by Tgrandis** [comment]
Hi Sam: 

Thanks for the reaction. I appreciate that. 

I will follow your suggestions when referencing the use of the
programme. 

Greetings, 

Hugo 

On 2021-09-19 12:34, Sam Hunter wrote:

> Hi Hugo, 
> 
> Thanks for your suggestion. I'm glad that HTStream has been useful for you, and thank you for acknowledging our hard work in making it available! Unfortunately we don't have a publication quite yet. Please just cite the GitHub page for now. I have updated the readme to reflect this, and also added a citation to an earlier implementation of the SuperDeduper algorithm. 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or unsubscribe [2].
> Triage notifications on the go with GitHub Mobile for iOS [3] or Android [4].

-- 
Hugo A. Volkaert
Center for Agricultural Biotechnology
Kasetsart University Kamphaengsaen Campus
Kamphaengsaen, Nakhonpathom
Thailand 73140
phone: +66 34353217
fax: +66 34353222 

Links:
------
[1]
https://secure-web.cisco.com/1GvqEmSDrSvMQ776XB2wwLaJ9xRpLTJlzv5JdOqreqQfU1UQKvbokaTII_55Z5BYwFI3qJV4wNCPoqUhOSbJjnIJAmdhQSUePMro174CNndNi9UmfL6Xeme_Xra98QTJ5exwKSMvCEP_f5zn8yusLYh9qvlMLt4GF6VOPS9gu6ExrmdPIRdHydnYS8bLpgqu-XX3S1rL9NCbdoWKwSYqFlUHI-o5hS_kUe6dUiBchv_nN0tT53jBYZnpj5GzTVAjaKViKzMsxiuxmzntD13gzXgJU2eMf18z0kxmFOERbIu4/https%3A%2F%2Fgithub.com%2Fs4hts%2FHTStream%2Fissues%2F245%23issuecomment-922418192
[2]
https://secure-web.cisco.com/1vCUDVvc2t3UO7yuRL23D35z083oGRLBqztZzkFloeV8D-sZ-x2gY82IDS3Vs5yevcmBTGTpuMVSEzdo4bHQcHmXU9hqqEJF0wOplMJYEq4-yNqmoEoeD7ihbA1QtQSiE5D43YBZ9R4WQIlFuMhl_B0VzQApoT0KVJis_kodGYi2p5QWLhu0D1HjE2md7PsZMwZ6uluZAquM74z8rn2SZ3ibOsv8GDK8_GCxznJlHyshXJvx0YguxGzLIf8gBSuSzexeCFyo1qQ57FVMufgroUGHxVO8gqCcg6LNjjLjQ-B8/https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FADIOC7LG274EL4OJ7AMDXATUCVY7RANCNFSM5ED4NKLQ
[3]
https://secure-web.cisco.com/15qvdGaeN0ft7_rR-JKvNpd7solFgqThyPCc_W3XopoGCTYKvr9kDZojVuis2yXjZycKVXsixZYL7IUPf8uAQTz4l4N6wPFCMRCs5teY0VCK9He3FbPch8Vj3v301T0FUcm7PoZOl-IpWjgsqkjsVSerdLj4QqHI0yH8sg2Fc8QycQj9pmNdG3McTf0ktR31wbJw3qqK8egnhNWYWLnb7QDJAGby3plHWTfUru1xh1UqEpyejl1MR4Zfuef8gY6vE2otmlGW9JLCQZVpwK_1kvMXnnpbdnyur5P9Xzz_tmW0/https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675
[4]
https://secure-web.cisco.com/1ZbpajWHBMOEN8fuAGbMpOPj6l7qmP2hYtDzVZaTGUN9o7pgW3vlmxm_cVBOmXXCSfqT03NRUvnFwJgcOBixDdbHA5fOA0btbPzKLmyofpcJtuMCZlNlcE3CI8tGjcxYrQOyMF5_4a81xq-DSj18-9e3MmG6YCgpXohVIxura8oRJVZgRFss0pgGV-Sr2XC2WXsNW9c6ItS144WGOGA2eQRkuSHtEHBa9ID35m5InpqXGKPrXLsZg9Z3x4YNCIYHzCB44reaG7oMg2zT6TN6nCTF2RKcCY4MbgIkBMAqP3KU/https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub
