### ISSUE TITLE
pointer error in hts_Stats

### ISSUE THREAD

**Issue by najoshi** [s4hts/HTStream#249]
So I am trying to run hts_Stats (in a pipeline) on an old fastq file.... it has quality values that use an offset of 64. This seems to be causing problems when running hts_Stats. I get this error:

*** Error in `hts_Stats': free(): invalid pointer: 0x0000000002487a71 ***
======= Backtrace: =========
[0x568e81]
[0x5713c6]
[0x575447]
[0x4386f0]
[0x43872c]
[0x438691]
[0x4384cd]
[0x40e99c]
[0x40a3a1]
[0x42ec98]
[0x42ecd0]
[0x434215]
[0x43331d]
[0x43211d]
[0x430e63]
[0x42f663]
[0x42ebe8]
[0x43b966]
[0x43b996]
[0x41741a]
[0x414199]
[0x410e1b]
[0x40d125]
[0x4013b5]
[0x546556]
[0x546b45]
[0x401159]
======= Memory map: ========
00400000-0069c000 r-xp 00000000 00:2f 502202560                          /afs/genomecenter.ucdavis.edu/software/htstream/1.3.3/lssc0-linux/bin/hts_Stats
0089c000-008a6000 rw-p 0029c000 00:2f 502202560                          /afs/genomecenter.ucdavis.edu/software/htstream/1.3.3/lssc0-linux/bin/hts_Stats
008a6000-008b0000 rw-p 00000000 00:00 0 
0245e000-024a2000 rw-p 00000000 00:00 0                                  [heap]
7f9378000000-7f9378033000 rw-p 00000000 00:00 0 
7f9378033000-7f937c000000 ---p 00000000 00:00 0 
7f937edfa000-7f937edfb000 rw-p 00000000 00:00 0 
7ffc2274f000-7ffc22770000 rw-p 00000000 00:00 0                          [stack]
7ffc227b8000-7ffc227bb000 r--p 00000000 00:00 0                          [vvar]
7ffc227bb000-7ffc227bd000 r-xp 00000000 00:00 0                          [vdso]
ffffffffff600000-ffffffffff601000 r-xp 00000000 00:00 0                  [vsyscall]
Aborted (core dumped)

Here is the command I ran:

hts_Stats -F -L test.log -1 test1.fq.gz -2 test2.fq.gz -f test

And I have attached the two fq files that reproduce the error. I'm running on Ubuntu 16.04 using htstream 1.3.3.

[test2.fq.gz](https://github.com/s4hts/HTStream/files/8222320/test2.fq.gz)
[test1.fq.gz](https://github.com/s4hts/HTStream/files/8222321/test1.fq.gz)

**Comment by joe-angell** [comment]
I've investigated this issue, looks like you are using quality scores outside the range we currently support, working on a fix now. @msettles
